### ISSUE TITLE
Documentation for tactics and definitions missing

### ISSUE THREAD

**Issue by b-reinke** [leanprover-community/NNG4#11]
At least in the version that is currently live on https://adam.math.hhu.de/#/g/hhu-adam/NNG4/, the documentation for the tactics and definitions in the "inventory" on the right side is missing. There are also some lemmas that have missing documentation.

**Comment by joneugster** [comment]
Thanks! There is right now a student working on refactoring the NNG  (as a summer project), adding new levels etc. and once they're done we'll make sure all the documentation in the "inventory" is also on par.

**Comment by joneugster** [comment]
Cleanup, this has been addressed a long time ago
