### ISSUE TITLE
No introduction of "backwards rewrite"

### ISSUE THREAD

**Issue by Madjosz** [leanprover-community/NNG4#28]
[Implication world, Level 4](https://adam.math.hhu.de/#/g/hhu-adam/NNG4/world/Implication/level/4)
After executing the `rw [four_eq_succ_three] at h` the next step in the guide writes
> Now rewrite succ_eq_add_one **backwards** at h to get the right hand side.

but nowhere before it is explained that **backwards** is done by `←`. I assume it was removed with #8. One can only see this by pressing "Show more help!" (which spoiles the whole solution) or reading the documentation of `rw`. While the latter is of course a crucial ability for using programming languages I would prefer to be taught this explicitly.

**Comment by joneugster** [comment]
Thanks for reporting, modified the hint message.

**Comment by Madjosz** [comment]
Fixed with d80a520359e306c4b050782f84a4c5fab6e4f71b
