### ISSUE TITLE
Pow.pow doesn't render infix

### ISSUE THREAD

**Issue by danielzgtg** [leanprover-community/NNG4#46]
The missing rendering support from `Pow.pow` to `^` makes things hard to read.

# Expected Behavior

```
Goal:
0 ^ 0 = 1
``` 

# Actual Behavior

![`Pow.pow 0 0 = 1`](https://github.com/leanprover-community/NNG4/assets/25646384/3263420d-c5a1-4e63-b3fc-5df4354cad67)

**Comment by joneugster** [comment]
Thanks! Should be fixed once the next version is uploaded.
