### ISSUE TITLE
You have not unlocked the tactic 'generalizing' yet! 

### ISSUE THREAD

**Issue by mfornet** [leanprover-community/NNG4#51]
In the level `mul_left_cancel` (level 9 | advanced multiplication world) we need to start the proof (as suggested by the hint) with:

```lean
induction b with h hd generalizing c
```

and the game emits the following warning:

```
You have not unlocked the tactic 'generalizing' yet!
```

**Comment by joneugster** [comment]
Thanks for the report! This is indeed already fixed and will be in the live version when updating that to lean `v4.6.0` at the end of the month.

**Comment by joneugster** [comment]
Should be fixed in the version online, since a few weeks ago. Please reopen if you still experience any issues!
