### ISSUE TITLE
There are bugs in generated pot file.

### ISSUE THREAD

**Issue by JiechengZhao** [leanprover-community/NNG4#56]
How to reproduce: `msginit --locale=zh_CN --input=.i18n/Game.pot --output=.i18n/Game-zh_CN.po` .

https://github.com/leanprover-community/NNG4/blob/18e0aec41dc63b71c774a40fbb551cedd7b209dc/.i18n/Game.pot#L54 
here no `\` berfore `"` in `"Goal"`. 

https://github.com/leanprover-community/NNG4/blob/18e0aec41dc63b71c774a40fbb551cedd7b209dc/.i18n/Game.pot#L76
The same.

https://github.com/leanprover-community/NNG4/blob/18e0aec41dc63b71c774a40fbb551cedd7b209dc/.i18n/Game.pot#L102
Should use `\\` in `\left` and `\l`.

https://github.com/leanprover-community/NNG4/blob/18e0aec41dc63b71c774a40fbb551cedd7b209dc/.i18n/Game.pot#L205
should be `\"\n`.

https://github.com/leanprover-community/NNG4/blob/18e0aec41dc63b71c774a40fbb551cedd7b209dc/.i18n/Game.pot#L240
The same, add `\` before `"`.

**Comment by joneugster** [comment]
Ill opened an issue over there and will fix this next week. Should be in the NNG when it updates to the next Lean toolchain
