### ISSUE TITLE
at h

### ISSUE THREAD

**Issue by jariji** [leanprover-community/NNG4#59]
https://adam.math.hhu.de/#/g/leanprover-community/nng4/world/Implication/level/2

> Rewrite `zero_add` at `h` twice, to change `h` into the goal.

Not sure we've heard about `at` yet.

**Comment by joneugster** [comment]
Already fixed a week ago, will be online in the next update. The first hint now says:

>You can use `rw [zero_add] at h` to rewrite at `h` instead
  of at the goal.
